/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Application;
import Model.VitalSignHistory;
import javax.swing.JOptionPane;

/**
 *
 * @author zequncao
 */
public class CreateJPanel extends javax.swing.JPanel {

    private Application application;

    /**
     * Creates new form CreateJPanel
     */

    CreateJPanel(Application application) {
        initComponents();
        
        this.application = application;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fieldObservationID = new javax.swing.JTextField();
        fieldTemperature = new javax.swing.JTextField();
        fieldBloodPressure = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("CREATE A VITAL SIGN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 160, 40));

        fieldObservationID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldObservationIDActionPerformed(evt);
            }
        });
        add(fieldObservationID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 150, 30));
        add(fieldTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 150, 30));
        add(fieldBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 160, 30));

        jLabel2.setText("ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jLabel3.setText("Temperature");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel4.setText("BloodPressure");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        
        // add an observation to vital signs history
        
        VitalSignHistory history = this.application.getHistory();
        
        // read the text fileds
        String id = fieldObservationID.getText();
        String temperature = fieldTemperature.getText();
        String bloodpressure = fieldBloodPressure.getText();
        
        // convert/cast and pass
        
        history.createObservation(Integer.valueOf(id), Double.valueOf(temperature), Double.valueOf(bloodpressure));
        
        JOptionPane.showMessageDialog(null,"Added observation");
    }//GEN-LAST:event_addBtnActionPerformed

    private void fieldObservationIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldObservationIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldObservationIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField fieldBloodPressure;
    private javax.swing.JTextField fieldObservationID;
    private javax.swing.JTextField fieldTemperature;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
