/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Customer;
import Model.DeliveryPackage;
import Model.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author zequncao
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private DeliveryPackage delPackage;
    
    private Boolean validate = false;
    
    private Boolean pvalidate = false;
    
    public CreateJPanel() {
        initComponents();
        
        
 
    }
    
    CreateJPanel(DeliveryPackage deliveryPackage) {
        initComponents();
        
        this.delPackage = deliveryPackage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        packageId = new javax.swing.JLabel();
        wt = new javax.swing.JLabel();
        prodId = new javax.swing.JLabel();
        prodName = new javax.swing.JLabel();
        prodPrice = new javax.swing.JLabel();
        custName = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        custId = new javax.swing.JLabel();
        SaveBtn = new javax.swing.JButton();
        prodsaveBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 110, -1));

        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 110, -1));

        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 110, -1));

        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 110, -1));

        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 110, -1));

        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField6FocusLost(evt);
            }
        });
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 100, -1));

        packageId.setText("Package Id");
        add(packageId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        wt.setText("Weight");
        add(wt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        prodId.setText("ProdId");
        add(prodId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        prodName.setText("ProdName");
        add(prodName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        prodPrice.setText("ProdPrice");
        add(prodPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, -1, -1));

        custName.setText("Customer Name");
        add(custName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        jTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField7FocusLost(evt);
            }
        });
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 100, -1));

        custId.setText("ID");
        add(custId, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        SaveBtn.setText("SAVE");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, -1));

        prodsaveBtn.setText("Save Product");
        prodsaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodsaveBtnActionPerformed(evt);
            }
        });
        add(prodsaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
        
        //Get the data;
        if(validate) {
            JOptionPane.showMessageDialog(null,"Please fill out all fields");
        } else {
            JOptionPane.showMessageDialog(null,"Saved Successfully");
        }
        
        String packageId = jTextField1.getText();
        String weight = jTextField2.getText();
        
        String customerId = jTextField6.getText();
        String customerName = jTextField7.getText();
        
        //Store the data;
        this.delPackage.setPackageId(Integer.valueOf(packageId));
        this.delPackage.setPackageWeight(Double.valueOf(weight));
        
        Customer customer = this.delPackage.getCustomer();
        customer.setFullName(customerName);
        customer.setCustomerId(Integer.valueOf(customerId));
        
        
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void prodsaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodsaveBtnActionPerformed
        // TODO add your handling code here:
        
        if(pvalidate) {
            JOptionPane.showMessageDialog(null,"Please fill out all fields");
        } else {
            JOptionPane.showMessageDialog(null,"Product Added");
        }
        
        String productId = jTextField3.getText();
        String productName = jTextField4.getText();
        String productPrice = jTextField5.getText();
        
        Product product = this.delPackage.createProduct(Integer.valueOf(productId), 
                productName, Double.valueOf(productPrice));
        

                 
    }//GEN-LAST:event_prodsaveBtnActionPerformed

    private void jTextField6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusLost
        // TODO add your handling code here:
        System.out.println(jTextField6.getText() + "");
        String name = jTextField6.getText();
        
        if(name.isEmpty()) {
            this.validate = true;
        } else {
            this.validate = false;
        }
    }//GEN-LAST:event_jTextField6FocusLost

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        System.out.println(jTextField1.getText() + "");
        String name = jTextField1.getText();
        
        if(name.isEmpty()) {
            this.validate = true;
        } else {
            this.validate = false;
        }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        // TODO add your handling code here:
        System.out.println(jTextField2.getText() + "");
        String name = jTextField2.getText();
        
        if(name.isEmpty()) {
            this.validate = true;
        } else {
            this.validate = false;
        }
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusLost
        // TODO add your handling code here:
        System.out.println(jTextField7.getText() + "");
        String name = jTextField7.getText();
        
        if(name.isEmpty()) {
            this.validate = true;
        } else {
            this.validate = false;
        }
    }//GEN-LAST:event_jTextField7FocusLost

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        // TODO add your handling code here:
        System.out.println(jTextField3.getText() + "");
        String name = jTextField3.getText();
        
        if(name.isEmpty()) {
            this.pvalidate = true;
        } else {
            this.pvalidate = false;
        }
    }//GEN-LAST:event_jTextField3FocusLost

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        // TODO add your handling code here:
        System.out.println(jTextField4.getText() + "");
        String name = jTextField4.getText();
        
        if(name.isEmpty()) {
            this.pvalidate = true;
        } else {
            this.pvalidate = false;
        }
    }//GEN-LAST:event_jTextField4FocusLost

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
        // TODO add your handling code here:
        System.out.println(jTextField5.getText() + "");
        String name = jTextField5.getText();
        
        if(name.isEmpty()) {
            this.pvalidate = true;
        } else {
            this.pvalidate = false;
        }
    }//GEN-LAST:event_jTextField5FocusLost
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveBtn;
    private javax.swing.JLabel custId;
    private javax.swing.JLabel custName;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel packageId;
    private javax.swing.JLabel prodId;
    private javax.swing.JLabel prodName;
    private javax.swing.JLabel prodPrice;
    private javax.swing.JButton prodsaveBtn;
    private javax.swing.JLabel wt;
    // End of variables declaration//GEN-END:variables
}
