/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Customer;
import Model.DeliveryPackage;
import Model.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author zequncao
 */
public class EditJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditJPanel
     */
    private DeliveryPackage delPackage;
    private Product productViewed;
    
    public EditJPanel() {
        initComponents();   
    }

    EditJPanel(DeliveryPackage deliveryPackage) {
        initComponents();
        
        this.delPackage = deliveryPackage;
        
        displayProductList();
        
        displayPackageDetails();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        packageId = new javax.swing.JLabel();
        wt = new javax.swing.JLabel();
        prodId = new javax.swing.JLabel();
        prodName = new javax.swing.JLabel();
        prodPrice = new javax.swing.JLabel();
        custName = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        custId = new javax.swing.JLabel();
        UpdateBtn = new javax.swing.JButton();
        prodsaveBtn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        showBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 110, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 110, -1));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 110, -1));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 110, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 110, -1));
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 100, -1));

        packageId.setText("Package Id");
        add(packageId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        wt.setText("Weight");
        add(wt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        prodId.setText("ProdId");
        add(prodId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        prodName.setText("ProdName");
        add(prodName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        prodPrice.setText("ProdPrice");
        add(prodPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, -1, -1));

        custName.setText("Customer Name");
        add(custName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 100, -1));

        custId.setText("ID");
        add(custId, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        UpdateBtn.setText("UPDATE");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });
        add(UpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, -1));

        prodsaveBtn.setText("SAVE PRODUCT");
        prodsaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodsaveBtnActionPerformed(evt);
            }
        });
        add(prodsaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, -1, -1));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 140, -1));

        showBtn.setText("SHOW");
        showBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBtnActionPerformed(evt);
            }
        });
        add(showBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:

        //Get the data;
        String packageId = jTextField1.getText();
        String weight = jTextField2.getText();

        String customerId = jTextField7.getText();
        String customerName = jTextField6.getText();

        //Store the data;
        this.delPackage.setPackageId(Integer.valueOf(packageId));
        this.delPackage.setPackageWeight(Double.valueOf(weight));

        Customer customer = this.delPackage.getCustomer();
        customer.setFullName(customerName);
        customer.setCustomerId(Integer.valueOf(customerId));
        
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void prodsaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodsaveBtnActionPerformed
        // TODO add your handling code here:
        
        this.productViewed.setProductName(jTextField4.getText());
        this.productViewed.setPrice(Double.valueOf(jTextField5.getText()));
    }//GEN-LAST:event_prodsaveBtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    public void displayProductList() {
        
        for (Product p: this.delPackage.getProductList()) {
            jComboBox1.addItem(p.getProductId());
        }
    }
    
        public void displayPackageDetails() {
        jTextField1.setText(String.valueOf(this.delPackage.getPackageId()));
        jTextField2.setText(String.valueOf(this.delPackage.getPackageWeight()));

        Customer customer = this.delPackage.getCustomer();
        jTextField7.setText(String.valueOf(customer.getCustomerId()));
        jTextField6.setText(customer.getFullName());

    }
        
    private void showBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBtnActionPerformed

        jTextField3.setEnabled(false);
        
        int pid = (int) jComboBox1.getSelectedItem();


        Product prod = this.delPackage.findProduct(pid);
         this.productViewed = prod;


        if (!prod.equals(null)) {
            jTextField3.setText(String.valueOf(pid));
            jTextField4.setText(prod.getProductName());
            jTextField5.setText(String.valueOf(prod.getPrice()));
        } else {
            JOptionPane.showMessageDialog(null, "Product not found");
        }
        
    }//GEN-LAST:event_showBtnActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JLabel custId;
    private javax.swing.JLabel custName;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel packageId;
    private javax.swing.JLabel prodId;
    private javax.swing.JLabel prodName;
    private javax.swing.JLabel prodPrice;
    private javax.swing.JButton prodsaveBtn;
    private javax.swing.JButton showBtn;
    private javax.swing.JLabel wt;
    // End of variables declaration//GEN-END:variables
}
