/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Address;
import Model.Contact;
import Model.Student;
import javax.swing.JOptionPane;

/**
 *
 * @author zequncao
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private Student student;
    
    public MainJFrame() {
        initComponents();
        
        this.student = new Student();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        CreateJPanel = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        CityState = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        LastName = new javax.swing.JLabel();
        ViewProfile = new javax.swing.JLabel();
        ZipCode = new javax.swing.JLabel();
        EmailID = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        NUID = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        CollegeName = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        StreetName = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        FirstName = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        AptNo = new javax.swing.JLabel();
        Phone = new javax.swing.JLabel();
        ViewJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        View = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CreateJPanel.setBackground(new java.awt.Color(204, 204, 204));
        CreateJPanel.setPreferredSize(new java.awt.Dimension(350, 500));
        CreateJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        CreateJPanel.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 89, 150, -1));
        CreateJPanel.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 369, 150, -1));

        saveBtn.setText("SAVE");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        CreateJPanel.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 404, -1, -1));

        CityState.setText("City/State");
        CreateJPanel.add(CityState, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 337, -1, -1));
        CreateJPanel.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 194, 150, -1));

        LastName.setText("Last Name");
        CreateJPanel.add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 127, -1, -1));

        ViewProfile.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        ViewProfile.setText("Create");
        CreateJPanel.add(ViewProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 6, -1, -1));

        ZipCode.setText("ZipCode");
        CreateJPanel.add(ZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 369, -1, -1));

        EmailID.setText("Email ID");
        CreateJPanel.add(EmailID, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 232, -1, -1));
        CreateJPanel.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 124, 150, -1));

        NUID.setText("NUID");
        CreateJPanel.add(NUID, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 57, -1, -1));
        CreateJPanel.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 264, 150, -1));
        CreateJPanel.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 229, 150, -1));

        CollegeName.setText("College Name");
        CreateJPanel.add(CollegeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 162, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        CreateJPanel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 54, 150, -1));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        CreateJPanel.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 299, 150, -1));

        StreetName.setText("Street Name");
        CreateJPanel.add(StreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 267, -1, -1));
        CreateJPanel.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 159, 150, -1));

        FirstName.setText("First Name");
        CreateJPanel.add(FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 92, -1, -1));
        CreateJPanel.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 334, 150, -1));

        AptNo.setText("Apt. No");
        CreateJPanel.add(AptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 302, -1, -1));

        Phone.setText("Phone");
        CreateJPanel.add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 197, -1, -1));

        jSplitPane1.setLeftComponent(CreateJPanel);

        ViewJPanel.setBackground(new java.awt.Color(204, 255, 204));
        ViewJPanel.setPreferredSize(new java.awt.Dimension(250, 500));
        ViewJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NUID");
        ViewJPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel2.setText("First Name");
        ViewJPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel3.setText("Last Name");
        ViewJPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel4.setText("College Name");
        ViewJPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel5.setText("Phone");
        ViewJPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel6.setText("Email ID");
        ViewJPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel7.setText("Street Name");
        ViewJPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel8.setText("Apt. No");
        ViewJPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel9.setText("City/State");
        ViewJPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabel10.setText("ZipCode");
        ViewJPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        View.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        View.setText("View");
        ViewJPanel.add(View, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jSplitPane1.setRightComponent(ViewJPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        String nuid = jTextField1.getText();
        String fname = jTextField2.getText();
        String lname = jTextField3.getText();
        String cname = jTextField4.getText();
        String phone = jTextField5.getText();
        String email = jTextField6.getText();
        String sname = jTextField7.getText();
        String aptno = jTextField8.getText();
        String city = jTextField9.getText();
        String zipcode = jTextField10.getText();
        
        this.student.setNuid(nuid);
        this.student.setFname(fname);
        this.student.setLname(lname);
        this.student.setCname(cname);
        
        Contact contact = this.student.getContact();
        contact.setPhone(phone);
        contact.setEmail(email);
        
        Address address = this.student.getAddress();
        address.setSname(sname);
        address.setAptno(aptno);
        address.setCity(city);
        address.setZipcode(zipcode);
        
        if(nuid.equals("")) {
            JOptionPane.showMessageDialog(null,"NUID IS REQUIRED");
        }
        if(fname.equals("")) {
            JOptionPane.showMessageDialog(null,"First Name IS REQUIRED");
        }
        if(lname.equals("")) {
            JOptionPane.showMessageDialog(null,"Last Name IS REQUIRED");
        }
        if(cname.equals("")) {
            JOptionPane.showMessageDialog(null,"College Name IS REQUIRED");
        }
        if(phone.equals("")) {
            JOptionPane.showMessageDialog(null,"Phone IS REQUIRED");
        }
        if(email.equals("")) {
            JOptionPane.showMessageDialog(null,"Email ID IS REQUIRED");
        }
        if(sname.equals("")) {
            JOptionPane.showMessageDialog(null,"Street Name IS REQUIRED");
        }
        if(aptno.equals("")) {
            JOptionPane.showMessageDialog(null,"Apt. No IS REQUIRED");
        }
        if(city.equals("")) {
            JOptionPane.showMessageDialog(null,"City/State IS REQUIRED");
        }
        if(zipcode.equals("")) {
            JOptionPane.showMessageDialog(null,"ZipCode IS REQUIRED");
        }
        
        display();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void display() {
        jLabel1.setText(this.student.getNuid());
        jLabel2.setText(this.student.getFname());
        jLabel3.setText(this.student.getLname());
        jLabel4.setText(this.student.getCname());
        
        jLabel5.setText(String.valueOf(this.student.getContact().getPhone()));
        jLabel6.setText(this.student.getContact().getEmail());
        
        jLabel7.setText(this.student.getAddress().getSname());
        jLabel8.setText(this.student.getAddress().getAptno());
        jLabel9.setText(this.student.getAddress().getCity());
        jLabel10.setText(this.student.getAddress().getZipcode());
    }
    
    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AptNo;
    private javax.swing.JLabel CityState;
    private javax.swing.JLabel CollegeName;
    private javax.swing.JPanel CreateJPanel;
    private javax.swing.JLabel EmailID;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel NUID;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel StreetName;
    private javax.swing.JLabel View;
    private javax.swing.JPanel ViewJPanel;
    private javax.swing.JLabel ViewProfile;
    private javax.swing.JLabel ZipCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
