/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Customer;
import Model.DeliveryPackage;
import Model.Product;

/**
 *
 * @author zequncao
 */
public class ViewJPanel extends javax.swing.JPanel {
    
    private DeliveryPackage delPackage;

    /**
     * Creates new form ViewJPanel
     */
    public ViewJPanel() {
        initComponents();
        
    }
    
    ViewJPanel(DeliveryPackage deliveryPackage) {
        initComponents();
        
        this.delPackage = deliveryPackage;
        display();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        packageId = new javax.swing.JLabel();
        wt = new javax.swing.JLabel();
        prodId = new javax.swing.JLabel();
        prodName = new javax.swing.JLabel();
        prodPrice = new javax.swing.JLabel();
        custName = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        custId = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 110, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 110, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 110, -1));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 110, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 110, -1));
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 100, -1));

        packageId.setText("Package Id");
        add(packageId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        wt.setText("Weight");
        add(wt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        prodId.setText("ProdId");
        add(prodId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        prodName.setText("ProdName");
        add(prodName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        prodPrice.setText("ProdPrice");
        add(prodPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        custName.setText("Customer Name");
        add(custName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 100, -1));

        custId.setText("ID");
        add(custId, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    public void display() {
        jTextField1.setText(String.valueOf(this.delPackage.getPackageId()));
        jTextField2.setText(String.valueOf(this.delPackage.getPackageWeight()));
        
        Customer customer = this.delPackage.getCustomer();
        jTextField7.setText(String.valueOf(customer.getCustomerId()));
        jTextField6.setText(customer.getFullName());
        
        }
    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel custId;
    private javax.swing.JLabel custName;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel packageId;
    private javax.swing.JLabel prodId;
    private javax.swing.JLabel prodName;
    private javax.swing.JLabel prodPrice;
    private javax.swing.JLabel wt;
    // End of variables declaration//GEN-END:variables
}
